# Generated by Django 4.1.1 on 2022-10-02 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0004_remove_pet_specie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('drugs', models.ManyToManyField(to='clinic.drug', verbose_name='Remédios')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.pet', verbose_name='Pet')),
                ('veterinary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.veterinary', verbose_name='Veterinário')),
            ],
        ),
    ]
