# Generated by Django 4.1.1 on 2022-10-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_pet_specie'),
        ('clinic', '0002_appointment_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.pet', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='veterinary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.veterinary', verbose_name='Veterinário'),
        ),
    ]
