# Generated by Django 4.1.1 on 2022-10-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_appointment_pet_alter_appointment_veterinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
    ]
