# Generated by Django 4.1.1 on 2022-10-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_appointment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='drugs',
            field=models.ManyToManyField(blank=True, null=True, to='clinic.drug', verbose_name='Remédios'),
        ),
    ]
