# Generated by Django 4.1.1 on 2022-10-01 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('district', models.CharField(max_length=255, verbose_name='Bairro')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(max_length=255, verbose_name='Estado')),
                ('zip', models.CharField(max_length=9, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.address', verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('specie', models.CharField(max_length=255, verbose_name='Espécie')),
                ('breed', models.CharField(max_length=255, verbose_name='Raça')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('owners', models.ManyToManyField(related_name='pets', to='client.client', verbose_name='Donos')),
            ],
        ),
    ]
