# Generated by Django 4.1.1 on 2022-10-02 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_pet_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='client.client', verbose_name='Dono'),
            preserve_default=False,
        ),
    ]
