# Generated by Django 4.1.1 on 2022-10-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_pet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='specie',
        ),
    ]
